name: Build ARM64 Driver

on:
  push:
    branches: [ "bsd" ]
  pull_request:
    branches: [ "bsd" ]

env:
  PROJECT_FILE_PATH: if_re.vcxproj
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: ARM64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download WDK Installer
      run: |
        curl -L -o wdksetup.exe "https://go.microsoft.com/fwlink/?linkid=2243392"

    - name: Install WDK
      run: |
        Start-Process -FilePath .\wdksetup.exe -ArgumentList "/q" -Wait
      shell: pwsh

    - name: Build ARM64 Driver
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.PROJECT_FILE_PATH}}
